### ISSUE TITLE
[S2-PBI5] Melakukan checkout kelas

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#14]

**Comment by FransiscusMichael** [comment]
![Image](https://user-images.githubusercontent.com/115627380/228794562-68ff097c-580e-4c27-996c-f07bc66d269a.png)

**Comment by aqilasalsblh** [comment]
![Image](https://github.com/SI-RPL-2023/SI4403_F_GURUBINTANG/assets/115602695/3b371aca-2b0f-4144-b192-98dfc93f5914)
