### ISSUE TITLE
[S1-PBI2] Melakukan login

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#2]

**Comment by amirahmahmd1** [comment]
![Image](https://user-images.githubusercontent.com/115637771/228791244-6ab825ca-8a8f-4d1f-b1d5-e2e3fab8130d.png)

**Comment by aqilasalsblh** [comment]
Activity Diagram



![Image](https://user-images.githubusercontent.com/115602695/229331147-8a9eb6e2-b685-49ba-bf91-7333a2ce6920.png)
