### ISSUE TITLE
[S3-PBI15] Melihat detail mentor

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#21]

**Comment by annisamiswanda** [comment]
activity diagram


![Image](https://user-images.githubusercontent.com/115612894/228792090-9b8420d6-e541-480b-ad91-11f7157de791.jpg)

**Comment by aqilasalsblh** [comment]
![Image](https://github.com/SI-RPL-2023/SI4403_F_GURUBINTANG/assets/115602695/95219015-50fe-44ba-8de6-5f7f2accbe7e)
