### ISSUE TITLE
[S3-PBI17] Melihat daftar transaksi

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#23]

**Comment by viradm334** [comment]
![Image](https://user-images.githubusercontent.com/115622602/229362273-144d3339-2657-412a-9304-0b91d1c3708d.png)

**Comment by aqilasalsblh** [comment]
![Image](https://github.com/SI-RPL-2023/SI4403_F_GURUBINTANG/assets/115602695/09f02b9a-1c07-4a89-8b9a-affda762f90f)
