### ISSUE TITLE
[S3-PBI24] Cetak sertifikat

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#30]

**Comment by viradm334** [comment]
![Image](https://user-images.githubusercontent.com/115622602/229363881-80aa02fc-0a39-4819-b9a0-eeb962825529.png)

**Comment by aqilasalsblh** [comment]
![Image](https://github.com/SI-RPL-2023/SI4403_F_GURUBINTANG/assets/115602695/05ca3c5e-9439-4a50-bf7d-4e213df5f2a1)
