### ISSUE TITLE
[S1-PBI4] Melihat list mentor

### ISSUE THREAD

**Issue by aqilasalsblh** [SI-RPL-2023/SI4403_F_GURUBINTANG#4]

**Comment by viradm334** [comment]
Activity Diagram

![Image](https://user-images.githubusercontent.com/115622602/228787610-9a2a4a80-87a3-4e80-afa1-fe8abe06af41.png)

**Comment by aqilasalsblh** [comment]
![Image](https://github.com/SI-RPL-2023/SI4403_F_GURUBINTANG/assets/115602695/99e155db-a8d0-4d03-b81d-e144df530e0f)
